mod settings;
mod types;

use anyhow::{Context, Result};
use specta::{
    ts::{BigIntExportBehavior, ExportConfiguration},
    DefOpts, NamedDataTypeItem, NamedType, TypeDefs,
};
use std::path::Path;

pub use settings::{default_prompt_template, AppSettings};
pub use types::*;

/// Render the TypeScript data contract consumed by the frontend.
///
/// Every Specta error is annotated with the failing type and returned. Keep
/// this list ordered: the checked-in file is an intentionally byte-stable
/// projection, not merely a set of equivalent declarations.
pub fn bindings_source() -> Result<String> {
    let configuration = ExportConfiguration::default().bigint(BigIntExportBehavior::Number);
    let mut exports = Vec::new();

    macro_rules! export {
        ($type:ty) => {
            exports.push(
                export_type::<$type>(&configuration, false)
                    .with_context(|| format!("export {}", stringify!($type)))?,
            );
        };
    }
    macro_rules! export_required {
        ($type:ty) => {
            exports.push(
                export_type::<$type>(&configuration, true)
                    .with_context(|| format!("export {}", stringify!($type)))?,
            );
        };
    }

    export!(symphony_core::AgentBackend);
    export!(symphony_core::CodexPermissionMode);
    export!(symphony_core::ThreadSandbox);
    export!(symphony_core::TurnSandboxPolicy);
    export!(symphony_core::ClaudePermissionMode);
    export!(symphony_core::CursorAgentMode);
    export!(symphony_core::CursorSandboxMode);
    // Serde defaults keep old settings files readable, but every command
    // response serializes a complete settings value. Preserve that stronger
    // outbound contract instead of projecting defaults as optional TS fields.
    export_required!(symphony_core::RepoConfig);
    export_required!(AppSettings);
    export!(SaveSettingsRequest);
    export!(TrackerTestResult);
    export!(LinearViewerProfile);
    export!(ValidationResult);
    export!(symphony_worker::WorkerState);
    export!(symphony_worker::WorkerStatus);
    export!(symphony_storage::RunWithIssueRow);
    export!(symphony_storage::RetryWithIssueRow);
    export!(symphony_storage::LiveSessionRow);
    export!(symphony_storage::RateLimitStateRow);
    export!(symphony_storage::WorkerHeartbeatRow);
    export!(symphony_storage::TokenUsageRow);
    export!(symphony_storage::Overview);
    export!(symphony_storage::RetroRow);
    export!(RetroRunState);
    export!(RetroStatus);
    export!(RetroDetail);
    export!(symphony_storage::RetroSuggestionRow);
    export!(symphony_storage::RetroBatchRow);
    export!(RetroReport);
    export!(RetroRepoReport);
    export!(RetroFinding);
    export!(RetroSeverity);
    export!(RetroEvidence);
    export!(RetroSuggestion);
    export!(RetroSuggestionTarget);
    export!(RetroConfidence);
    export!(symphony_storage::IssueRow);
    export!(symphony_storage::AgentEventRow);
    export!(symphony_storage::StorageEvent);
    export!(symphony_worker::SkillsState);
    export!(symphony_worker::SkillsStatus);
    export!(symphony_worker::SkillsInstallState);
    export!(symphony_worker::SkillsInstallStatus);
    export!(symphony_worker::RepoWorkflowSource);
    export!(symphony_worker::RepoWorkflowStatus);
    export!(symphony_worker::WorkflowTransferState);
    export!(symphony_worker::WorkflowTransferStatus);
    export!(RunDetail);
    export!(IssueDetail);

    Ok(format!(
        "// Generated by symphony-contracts. Do not edit by hand.\n{}\n",
        exports.join("\n\n")
    ))
}

fn export_type<T: NamedType>(
    configuration: &ExportConfiguration,
    required_fields: bool,
) -> Result<String> {
    let mut definitions = TypeDefs::default();
    let mut datatype = T::definition_named_data_type(DefOpts {
        parent_inline: false,
        type_map: &mut definitions,
    })?;
    if required_fields {
        let NamedDataTypeItem::Object(object) = &mut datatype.item else {
            anyhow::bail!("required-field export is only valid for named structs");
        };
        for field in &mut object.fields {
            field.optional = false;
        }
    }
    Ok(specta::ts::export_datatype(configuration, &datatype)?)
}

/// Export bindings to an explicit destination for desktop development and CI.
pub fn export_bindings(path: impl AsRef<Path>) -> Result<()> {
    let path = path.as_ref();
    let source = bindings_source()?;
    std::fs::write(path, source)
        .with_context(|| format!("write generated bindings to {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bindings_are_deterministic() {
        assert_eq!(bindings_source().unwrap(), bindings_source().unwrap());
    }

    #[test]
    fn write_failures_are_returned() {
        let directory = tempfile::tempdir().unwrap();
        let error = export_bindings(directory.path()).unwrap_err().to_string();
        assert!(error.contains("write generated bindings"));
        assert!(error.contains(&directory.path().display().to_string()));
    }
}
