// Generated by symphony-contracts. Do not edit by hand.
export type AgentBackend = "codex" | "claude" | "cursor" | "opencode"

export type CodexPermissionMode = "approve-for-me" | "full-access"

export type ThreadSandbox = "none" | "workspace-write" | "read-only"

export type TurnSandboxPolicy = "inherit" | "workspace-write" | "read-only" | "danger-full-access"

export type ClaudePermissionMode = "default" | "acceptEdits" | "auto" | "bypassPermissions" | "dontAsk" | "plan"

export type CursorAgentMode = "agent" | "plan" | "ask"

export type CursorSandboxMode = "enabled" | "disabled"

/**
 * One repository Symphony can dispatch runs into. `name` doubles as the
 * routing key (`repo:<name>` or bare `<name>` labels in Linear) and the
 * workspace namespace, so it must be unique across the configured repos.
 */
export type RepoConfig = { name: string; url: string; install_cmd: string | null; is_default: boolean; skills_marked_installed: boolean }

/**
 * Structured app settings — the single source of truth for worker, tracker,
 * and agent configuration. Defaults mirror the workflow Symphony used to
 * ship as a YAML front matter (states, hooks, sandbox/permission options).
 */
export type AppSettings = { prompt_template: string; repos: RepoConfig[]; workspace_root: string | null; tracker_workspace: string | null; tracker_team_keys: string[]; tracker_project_ids: string[]; tracker_assigned_to_me: boolean; active_states: string[]; terminal_states: string[]; polling_interval_ms: number; max_concurrent_agents: number; max_retry_backoff_ms: number; hook_after_create: string | null; hook_before_run: string | null; hook_after_run: string | null; hook_timeout_ms: number; agent_backend: AgentBackend; codex_command: string | null; claude_command: string | null; turn_timeout_ms: number; session_env: { [key: string]: string }; codex_permission_mode: CodexPermissionMode; codex_thread_sandbox: ThreadSandbox; codex_turn_sandbox_policy: TurnSandboxPolicy; codex_network_access: boolean; claude_permission_mode: ClaudePermissionMode; claude_allowed_tools: string[]; claude_disallowed_tools: string[]; claude_add_dirs: string[]; cursor_command: string | null; cursor_mode: CursorAgentMode; cursor_force: boolean; cursor_trust: boolean; cursor_approve_mcps: boolean; cursor_sandbox: CursorSandboxMode; cursor_model: string | null; opencode_command: string | null; opencode_model: string | null; opencode_agent: string | null; opencode_skip_permissions: boolean; linear_api_key_set: boolean }

export type SaveSettingsRequest = { settings: AppSettings; linear_api_key: string | null }

export type TrackerTestResult = { ok: boolean; message: string; active_issue_count: number | null }

export type LinearViewerProfile = { id: string; username: string; display_name: string | null; email: string | null }

/**
 * A Linear workflow state, projected as a Kanban column for the Issues board.
 */
export type WorkflowStateRow = { id: string; name: string; state_type: string; position: number }

export type ValidationResult = { workflow_ok: boolean; workflow_blocking: boolean; workflow_error: string | null; codex_found: boolean; claude_found: boolean; cursor_found: boolean; opencode_found: boolean; codex_command: string; claude_command: string; cursor_command: string; opencode_command: string; app_data_dir: string; database_path: string }

export type WorkerState = "stopped" | "running" | "stopping"

export type WorkerStatus = { state: WorkerState; started_at: string | null; last_error: string | null }

export type RunWithIssueRow = { id: string; issue_id: string; run_number: number; workspace_path: string; status: string; started_at: string | null; ended_at: string | null; error_class: string | null; error_message: string | null; worker_pid: number | null; session_info: string | null; repo_name: string | null; created_at: string; issue_identifier: string; issue_title: string; issue_state: string }

export type RetryWithIssueRow = { issue_id: string; run_number: number; due_at: string; error_class: string | null; error_message: string | null; created_at: string; issue_identifier: string; issue_title: string }

export type LiveSessionRow = { run_id: string; session_id: string; thread_id: string; turn_id: string; input_tokens: number; output_tokens: number; total_tokens: number; last_event_at: string; started_at: string }

export type RateLimitStateRow = { source: string; remaining: number | null; reset_at: string | null; updated_at: string }

export type TokenUsageRow = { source: string; input_tokens: number; output_tokens: number; total_tokens: number; run_count: number; updated_at: string }

export type Overview = { active_runs: RunWithIssueRow[]; retry_queue: RetryWithIssueRow[]; retry_count: number; recent_failures: RunWithIssueRow[]; failure_count: number; workspace_cleanup_count: number; live_sessions: LiveSessionRow[]; rate_limits: RateLimitStateRow[]; token_usage: TokenUsageRow[] }

export type RetroRow = { id: string; since_at: string; until_at: string; status: string; run_count: number; issue_count: number; report_json: string | null; error_message: string | null; created_at: string; completed_at: string | null }

export type RetroRunState = "idle" | "running" | "completed" | "failed"

export type RetroStatus = { state: RetroRunState; retro_id: string | null; message: string | null; report: RetroReport | null; error: string | null }

export type RetroDetail = { row: RetroRow; report: RetroReport | null; suggestions: RetroSuggestionRow[]; batches: RetroBatchRow[] }

export type RetroSuggestionRow = { id: string; retro_id: string; repo_name: string; repo_url: string | null; finding_index: number; target_type: string; target_id: string; target_path: string; title: string; body: string; rationale: string; confidence: string; guidance: string; before_content: string | null; after_content: string | null; unified_diff: string | null; base_ref: string | null; base_hash: string | null; proposal_status: string; proposal_error: string | null; decision: string; decided_at: string | null; created_at: string }

export type RetroBatchRow = { id: string; retro_id: string; kind: string; repo_name: string | null; repo_url: string | null; base_ref: string | null; state: string; progress: string | null; error: string | null; pr_url: string | null; created_at: string; completed_at: string | null }

export type RetroReport = { id: string; since_at: string; until_at: string; generated_at: string; run_count: number; issue_count: number; workpad_count: number; repos: RetroRepoReport[] }

export type RetroRepoReport = { repo_name: string; run_count: number; issue_count: number; workpad_count: number; failure_count: number; retry_count: number; findings: RetroFinding[]; suggestions: RetroSuggestion[] }

export type RetroFinding = { title: string; detail: string; severity: RetroSeverity; occurrences: number; evidence: RetroEvidence[] }

export type RetroSeverity = "low" | "medium" | "high"

export type RetroEvidence = { issue_identifier: string; run_id: string | null; run_number: number | null; event_id: number | null; kind: string; summary: string }

export type RetroSuggestion = { target_type: RetroSuggestionTarget; target_id: string; title: string; body: string; rationale: string; confidence: RetroConfidence }

export type RetroSuggestionTarget = "prompt" | "skill"

export type RetroConfidence = "low" | "medium" | "high"

export type IssueRow = { id: string; identifier: string; title: string; description: string | null; priority: number; state: string; branch: string | null; labels: string; blockers: string; pr_urls: string; raw: string; last_seen_at: string }

export type AgentEventRow = { id: number; run_id: string; kind: string; payload: string; created_at: string }

export type StorageEvent = { type: "db_changed"; table: string; op: string } | { type: "agent_event"; event: AgentEventRow } | { type: "rate_limit_changed"; source: string }

export type SkillsState = "installed" | "pr_open" | "missing" | "unavailable"

export type SkillsStatus = { state: SkillsState; missing: string[]; pr_url: string | null; detail: string | null }

export type SkillsInstallState = "idle" | "running" | "completed" | "failed"

export type SkillsInstallStatus = { state: SkillsInstallState; repo_url: string | null; message: string | null; pr_url: string | null; error: string | null }

/**
 * One bundled skill: `name` is the directory under `.agents/skills/`,
 * `content` the full SKILL.md body.
 */
export type SkillFile = { name: string; content: string }

export type RepoWorkflowSource = "repository" | "default" | "unknown"

export type RepoWorkflowStatus = { source: RepoWorkflowSource; filename: string | null; fallback_reason: string | null; detail: string | null; pr_url: string | null; can_transfer: boolean }

export type WorkflowTransferState = "idle" | "running" | "completed" | "failed"

export type WorkflowTransferStatus = { state: WorkflowTransferState; repo_url: string | null; message: string | null; pr_url: string | null; error: string | null }

export type RunDetail = { run: RunWithIssueRow; events: AgentEventRow[] }

export type IssueDetail = { issue: IssueRow }
